### ISSUE TITLE
MakeCert has been deprecated

### ISSUE THREAD

**Issue by Offbeatmammal** [jasonjoh/node-service#1]
can still be installed from .Net4 Tools but might want to modify instructions to support the new powershell option

**Comment by jasonjoh** [comment]
Thanks for the suggestion! I'm not familiar, what's this PS option?

**Comment by Offbeatmammal** [comment]
https://technet.microsoft.com/library/hh848633 though I've not had a chance to run through and work out the relevant options yet (I grabbed the old makecert from the .net4 tools and it still seems to run fine on Win10)

**Comment by jasonjoh** [comment]
Thanks! I'll give this a whirl and see what's needed.

**Comment by lehtu** [comment]
*TESTED AND WORKING*
On Windows 8.1 you can use `New-SelfSignedCertificate` instead.
Here is working line for creating needed certificate:
```
New-SelfSignedCertificate -DnsName "Contoso AppName Cert" -CertStoreLocation "Cert:\CurrentUser\My"
```
Algorithm is RSA by default, also key length is 2048 by default and default expiration time is one year.

*NOT TESTED*
With older `New-SelfSignedCertificate` you should be able to use something like following:
```
New-SelfSignedCertificate -Subject "CN=Contoso AppName Cert" -KeyExportPolicy Exportable -KeyAlgorithm RSA -KeyLength 2048 -CertStoreLocation "Cert:\CurrentUser\My" -NotAfter (Get-Date).AddMonths(24)
```

**Comment by jasonjoh** [comment]
Thanks @lehtu. I just tested your "TESTED AND WORKING" method as well and it works fine. I'm going to add that as an alternative to the README.
